name: Test
on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'index.js'
      - 'test/**.js'
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'index.js'
      - 'test/**.js'
permissions:
  contents: read

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   name: Lint JS-Files
  #   steps:
  #     - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

  #     - name: Setup node
  #       uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
  #       with:
  #         node-version: 14

  #     - run: npm install

  #     - name: Lint JS-Files
  #       run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14, 16, 18]
        include:
          - node: 16
            coverage: true
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - name: NPM Test
        run: npm run test-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v1

  dependency-review:
    name: Dependency Review
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Dependency review
        uses: actions/dependency-review-action@v3
